/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultorio;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 169121742018.2
 */
public class ListagemJ extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListagemJ
     */
    public ListagemJ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonListagem = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jButtonListagem.setText("Listagem");
        jButtonListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButtonListagem)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButtonListagem)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListagemActionPerformed
        try {
            //Registra JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            //Abrindo a conexão
            Connection conn;
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/consultorio?useTimezone=true&serverTimezone=UTC", "root", "");

            //Executa a query de seleção
            java.sql.Statement st = conn.createStatement();
            st.executeQuery("select * from paciente");
            ResultSet rs = st.getResultSet();

            //Lista os alunos no console
            while (rs.next()) {
                JOptionPane.showMessageDialog(rootPane,"ID: " + rs.getString("ID") + "\n"
                + "Nome: "+ rs.getString("Nome") + "\n"
                + "CPF: "+ rs.getString("CPF") + "\n"
                +"Consulta: "+ rs.getString("Consulta") + "\n"
                +"Data da consulta: "+ rs.getString("Dataconsulta") + "\n"
                +"Horário da Consulta: "+ rs.getString("Horario"));
            }

        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButtonListagemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListagem;
    // End of variables declaration//GEN-END:variables
}
